
package org.engineeringnotebook.graphmanagerservice.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "GraphManagerWSEndpointImplService", targetNamespace = "http://ws.graphmanagerservice.engineeringnotebook.org/", wsdlLocation = "http://localhost:8080/GraphManagerService/GraphManagerWSEndpointImplService?wsdl")
public class GraphManagerWSEndpointImplService
    extends Service
{

    private final static URL GRAPHMANAGERWSENDPOINTIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.engineeringnotebook.graphmanagerservice.ws.GraphManagerWSEndpointImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.engineeringnotebook.graphmanagerservice.ws.GraphManagerWSEndpointImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/GraphManagerService/GraphManagerWSEndpointImplService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/GraphManagerService/GraphManagerWSEndpointImplService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GRAPHMANAGERWSENDPOINTIMPLSERVICE_WSDL_LOCATION = url;
    }

    public GraphManagerWSEndpointImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GraphManagerWSEndpointImplService() {
        super(GRAPHMANAGERWSENDPOINTIMPLSERVICE_WSDL_LOCATION, new QName("http://ws.graphmanagerservice.engineeringnotebook.org/", "GraphManagerWSEndpointImplService"));
    }

    /**
     * 
     * @return
     *     returns GraphManagerWSEndpoint
     */
    @WebEndpoint(name = "GraphManagerWSEndpointImplPort")
    public GraphManagerWSEndpoint getGraphManagerWSEndpointImplPort() {
        return super.getPort(new QName("http://ws.graphmanagerservice.engineeringnotebook.org/", "GraphManagerWSEndpointImplPort"), GraphManagerWSEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GraphManagerWSEndpoint
     */
    @WebEndpoint(name = "GraphManagerWSEndpointImplPort")
    public GraphManagerWSEndpoint getGraphManagerWSEndpointImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.graphmanagerservice.engineeringnotebook.org/", "GraphManagerWSEndpointImplPort"), GraphManagerWSEndpoint.class, features);
    }

}
